# -*- coding: utf-8 -*-
"""cantidadDeCommits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8ppSpDOea6S31bG_UAMESq0SFGP_4QQ
"""

text = '''commit 454c0b2e7e000fda7000cba49027541fbf327b96
Merge: 03da34c5 c3f4591f
Author: ZeroNet <HelloZeroNet@users.noreply.github.com>
Date:   Mon Jan 25 03:24:19 2021 +0100

    Merge pull request #2716 from imachug/uifile-404-fix
    
    Fix 404 error handler in UiFilePlugin

commit 03da34c5d6cd91b2e0ab913f1e2abbe233a20fa2
Merge: b4f4c125 3ad7bc87
Author: ZeroNet <HelloZeroNet@users.noreply.github.com>
Date:   Mon Jan 25 03:23:46 2021 +0100

    Merge pull request #2714 from timgates42/bugfix_typo_positive
    
    docs: fix simple typo, positibe -> positive

commit c3f4591f91025ea5b461f3e8042d47b40632e589
Author: Ivanq <imachug@yandex.ru>
Date:   Sun Dec 27 13:25:18 2020 +0300

    Fix 404 error handler in UiFilePlugin
    Merge pull request #2695 from kabitofu/test
    
    Japanese Translation '''

lista=text.split("commit")
print(len(lista)-1)