# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dyrJubWTgUEZsvrGGcZeOpKFAogRDxVB
"""

text = '''commit 454c0b2e7e000fda7000cba49027541fbf327b96
Merge: 03da34c5 c3f4591f
Author: ZeroNet <HelloZeroNet@users.noreply.github.com>
Date:   Mon Jan 25 03:24:19 2021 +0100

    Merge pull request #2716 from imachug/uifile-404-fix
    
    Fix 404 error handler in UiFilePlugin'''

text.split("Date")[1]

variable1 = text.split("Date")[1]

variable2 = variable1.split("/n")[2:]

variable2

variable3 = " ".join(variable2)

variable3